name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/0xcaff/app:latest
      - name: Build and Push image
        run: |
          docker buildx build \
            --file ./images/Containerfile \
            --platform linux/arm64,linux/amd64\
            --tag quay.io/user/tools:${{ steps.date.outputs.date }} \
            --push .
